DECORATIONS = [
    "DECOR_NONE",
    "DECOR_SMALL_DESK",
    "DECOR_POKEMON_DESK",
    "DECOR_HEAVY_DESK",
    "DECOR_RAGGED_DESK",
    "DECOR_COMFORT_DESK",
    "DECOR_PRETTY_DESK",
    "DECOR_BRICK_DESK",
    "DECOR_CAMP_DESK",
    "DECOR_HARD_DESK",
    "DECOR_SMALL_CHAIR",
    "DECOR_POKEMON_CHAIR",
    "DECOR_HEAVY_CHAIR",
    "DECOR_PRETTY_CHAIR",
    "DECOR_COMFORT_CHAIR",
    "DECOR_RAGGED_CHAIR",
    "DECOR_BRICK_CHAIR",
    "DECOR_CAMP_CHAIR",
    "DECOR_HARD_CHAIR",
    "DECOR_RED_PLANT",
    "DECOR_TROPICAL_PLANT",
    "DECOR_PRETTY_FLOWERS",
    "DECOR_COLORFUL_PLANT",
    "DECOR_BIG_PLANT",
    "DECOR_GORGEOUS_PLANT",
    "DECOR_RED_BRICK",
    "DECOR_YELLOW_BRICK",
    "DECOR_BLUE_BRICK",
    "DECOR_RED_BALLOON",
    "DECOR_BLUE_BALLOON",
    "DECOR_YELLOW_BALLOON",
    "DECOR_RED_TENT",
    "DECOR_BLUE_TENT",
    "DECOR_SOLID_BOARD",
    "DECOR_SLIDE",
    "DECOR_FENCE_LENGTH",
    "DECOR_FENCE_WIDTH",
    "DECOR_TIRE",
    "DECOR_STAND",
    "DECOR_MUD_BALL",
    "DECOR_BREAKABLE_DOOR",
    "DECOR_SAND_ORNAMENT",
    "DECOR_SILVER_SHIELD",
    "DECOR_GOLD_SHIELD",
    "DECOR_GLASS_ORNAMENT",
    "DECOR_TV",
    "DECOR_ROUND_TV",
    "DECOR_CUTE_TV",
    "DECOR_GLITTER_MAT",
    "DECOR_JUMP_MAT",
    "DECOR_SPIN_MAT",
    "DECOR_C_LOW_NOTE_MAT",
    "DECOR_D_NOTE_MAT",
    "DECOR_E_NOTE_MAT",
    "DECOR_F_NOTE_MAT",
    "DECOR_G_NOTE_MAT",
    "DECOR_A_NOTE_MAT",
    "DECOR_B_NOTE_MAT",
    "DECOR_C_HIGH_NOTE_MAT",
    "DECOR_SURF_MAT",
    "DECOR_THUNDER_MAT",
    "DECOR_FIRE_BLAST_MAT",
    "DECOR_POWDER_SNOW_MAT",
    "DECOR_ATTRACT_MAT",
    "DECOR_FISSURE_MAT",
    "DECOR_SPIKES_MAT",
    "DECOR_BALL_POSTER",
    "DECOR_GREEN_POSTER",
    "DECOR_RED_POSTER",
    "DECOR_BLUE_POSTER",
    "DECOR_CUTE_POSTER",
    "DECOR_PIKA_POSTER",
    "DECOR_LONG_POSTER",
    "DECOR_SEA_POSTER",
    "DECOR_SKY_POSTER",
    "DECOR_KISS_POSTER",
    "DECOR_PICHU_DOLL",
    "DECOR_PIKACHU_DOLL",
    "DECOR_MARILL_DOLL",
    "DECOR_TOGEPI_DOLL",
    "DECOR_CYNDAQUIL_DOLL",
    "DECOR_CHIKORITA_DOLL",
    "DECOR_TOTODILE_DOLL",
    "DECOR_JIGGLYPUFF_DOLL",
    "DECOR_MEOWTH_DOLL",
    "DECOR_CLEFAIRY_DOLL",
    "DECOR_DITTO_DOLL",
    "DECOR_SMOOCHUM_DOLL",
    "DECOR_TREECKO_DOLL",
    "DECOR_TORCHIC_DOLL",
    "DECOR_MUDKIP_DOLL",
    "DECOR_DUSKULL_DOLL",
    "DECOR_WYNAUT_DOLL",
    "DECOR_BALTOY_DOLL",
    "DECOR_KECLEON_DOLL",
    "DECOR_AZURILL_DOLL",
    "DECOR_SKITTY_DOLL",
    "DECOR_SWABLU_DOLL",
    "DECOR_GULPIN_DOLL",
    "DECOR_LOTAD_DOLL",
    "DECOR_SEEDOT_DOLL",
    "DECOR_PIKA_CUSHION",
    "DECOR_ROUND_CUSHION",
    "DECOR_KISS_CUSHION",
    "DECOR_ZIGZAG_CUSHION",
    "DECOR_SPIN_CUSHION",
    "DECOR_DIAMOND_CUSHION",
    "DECOR_BALL_CUSHION",
    "DECOR_GRASS_CUSHION",
    "DECOR_FIRE_CUSHION",
    "DECOR_WATER_CUSHION",
    "DECOR_SNORLAX_DOLL",
    "DECOR_RHYDON_DOLL",
    "DECOR_LAPRAS_DOLL",
    "DECOR_VENUSAUR_DOLL",
    "DECOR_CHARIZARD_DOLL",
    "DECOR_BLASTOISE_DOLL",
    "DECOR_WAILMER_DOLL",
    "DECOR_REGIROCK_DOLL",
    "DECOR_REGICE_DOLL",
    "DECOR_REGISTEEL_DOLL",
]

NAMES = {
    "DECOR_NONE": "None",
    "DECOR_SMALL_DESK": "Small Desk",
    "DECOR_POKEMON_DESK": "Pokémon Desk",
    "DECOR_HEAVY_DESK": "Heavy Desk",
    "DECOR_RAGGED_DESK": "Ragged Desk",
    "DECOR_COMFORT_DESK": "Comfort Desk",
    "DECOR_PRETTY_DESK": "Pretty Desk",
    "DECOR_BRICK_DESK": "Brick Desk",
    "DECOR_CAMP_DESK": "Camp Desk",
    "DECOR_HARD_DESK": "Hard Desk",
    "DECOR_SMALL_CHAIR": "Small Chair",
    "DECOR_POKEMON_CHAIR": "Pokémon Chair",
    "DECOR_HEAVY_CHAIR": "Heavy Chair",
    "DECOR_PRETTY_CHAIR": "Pretty Chair",
    "DECOR_COMFORT_CHAIR": "Comfort Chair",
    "DECOR_RAGGED_CHAIR": "Ragged Chair",
    "DECOR_BRICK_CHAIR": "Brick Chair",
    "DECOR_CAMP_CHAIR": "Camp Chair",
    "DECOR_HARD_CHAIR": "Hard Chair",
    "DECOR_RED_PLANT": "Red Plant",
    "DECOR_TROPICAL_PLANT": "Tropical Plant",
    "DECOR_PRETTY_FLOWERS": "Pretty Flowers",
    "DECOR_COLORFUL_PLANT": "Colorful Plant",
    "DECOR_BIG_PLANT": "Big Plant",
    "DECOR_GORGEOUS_PLANT": "Gorgeous Plant",
    "DECOR_RED_BRICK": "Red Brick",
    "DECOR_YELLOW_BRICK": "Yellow Brick",
    "DECOR_BLUE_BRICK": "Blue Brick",
    "DECOR_RED_BALLOON": "Red Balloon",
    "DECOR_BLUE_BALLOON": "Blue Balloon",
    "DECOR_YELLOW_BALLOON": "Yellow Balloon",
    "DECOR_RED_TENT": "Red Tent",
    "DECOR_BLUE_TENT": "Blue Tent",
    "DECOR_SOLID_BOARD": "Solid Board",
    "DECOR_SLIDE": "Slide",
    "DECOR_FENCE_LENGTH": "Fence Length",
    "DECOR_FENCE_WIDTH": "Fence Width",
    "DECOR_TIRE": "Tire",
    "DECOR_STAND": "Stand",
    "DECOR_MUD_BALL": "Mud Ball",
    "DECOR_BREAKABLE_DOOR": "Breakable Door",
    "DECOR_SAND_ORNAMENT": "Sand Ornament",
    "DECOR_SILVER_SHIELD": "Silver Shield",
    "DECOR_GOLD_SHIELD": "Gold Shield",
    "DECOR_GLASS_ORNAMENT": "Glass Ornament",
    "DECOR_TV": "TV",
    "DECOR_ROUND_TV": "Round TV",
    "DECOR_CUTE_TV": "Cute TV",
    "DECOR_GLITTER_MAT": "Glitter Mat",
    "DECOR_JUMP_MAT": "Jump Mat",
    "DECOR_SPIN_MAT": "Spin Mat",
    "DECOR_C_LOW_NOTE_MAT": "C Low Note Mat",
    "DECOR_D_NOTE_MAT": "D Note Mat",
    "DECOR_E_NOTE_MAT": "E Note Mat",
    "DECOR_F_NOTE_MAT": "F Note Mat",
    "DECOR_G_NOTE_MAT": "G Note Mat",
    "DECOR_A_NOTE_MAT": "A Note Mat",
    "DECOR_B_NOTE_MAT": "B Note Mat",
    "DECOR_C_HIGH_NOTE_MAT": "C High Note Mat",
    "DECOR_SURF_MAT": "Surf Mat",
    "DECOR_THUNDER_MAT": "Thunder Mat",
    "DECOR_FIRE_BLAST_MAT": "Fire Blast Mat",
    "DECOR_POWDER_SNOW_MAT": "Powder Snow Mat",
    "DECOR_ATTRACT_MAT": "Attract Mat",
    "DECOR_FISSURE_MAT": "Fissure Mat",
    "DECOR_SPIKES_MAT": "Spikes Mat",
    "DECOR_BALL_POSTER": "Ball Poster",
    "DECOR_GREEN_POSTER": "Green Poster",
    "DECOR_RED_POSTER": "Red Poster",
    "DECOR_BLUE_POSTER": "Blue Poster",
    "DECOR_CUTE_POSTER": "Cute Poster",
    "DECOR_PIKA_POSTER": "Pika Poster",
    "DECOR_LONG_POSTER": "Long Poster",
    "DECOR_SEA_POSTER": "Sea Poster",
    "DECOR_SKY_POSTER": "Sky Poster",
    "DECOR_KISS_POSTER": "Kiss Poster",
    "DECOR_PICHU_DOLL": "Pichu Doll",
    "DECOR_PIKACHU_DOLL": "Pikachu Doll",
    "DECOR_MARILL_DOLL": "Marill Doll",
    "DECOR_TOGEPI_DOLL": "Togepi Doll",
    "DECOR_CYNDAQUIL_DOLL": "Cyndaquil Doll",
    "DECOR_CHIKORITA_DOLL": "Chikorita Doll",
    "DECOR_TOTODILE_DOLL": "Totodile Doll",
    "DECOR_JIGGLYPUFF_DOLL": "Jigglypuff Doll",
    "DECOR_MEOWTH_DOLL": "Meowth Doll",
    "DECOR_CLEFAIRY_DOLL": "Clefairy Doll",
    "DECOR_DITTO_DOLL": "Ditto Doll",
    "DECOR_SMOOCHUM_DOLL": "Smoochum Doll",
    "DECOR_TREECKO_DOLL": "Treecko Doll",
    "DECOR_TORCHIC_DOLL": "Torchic Doll",
    "DECOR_MUDKIP_DOLL": "Mudkip Doll",
    "DECOR_DUSKULL_DOLL": "Duskull Doll",
    "DECOR_WYNAUT_DOLL": "Wynaut Doll",
    "DECOR_BALTOY_DOLL": "Baltoy Doll",
    "DECOR_KECLEON_DOLL": "Kecleon Doll",
    "DECOR_AZURILL_DOLL": "Azurill Doll",
    "DECOR_SKITTY_DOLL": "Skitty Doll",
    "DECOR_SWABLU_DOLL": "Swablu Doll",
    "DECOR_GULPIN_DOLL": "Gulpin Doll",
    "DECOR_LOTAD_DOLL": "Lotad Doll",
    "DECOR_SEEDOT_DOLL": "Seedot Doll",
    "DECOR_PIKA_CUSHION": "Pika Cushion",
    "DECOR_ROUND_CUSHION": "Round Cushion",
    "DECOR_KISS_CUSHION": "Kiss Cushion",
    "DECOR_ZIGZAG_CUSHION": "Zigzag Cushion",
    "DECOR_SPIN_CUSHION": "Spin Cushion",
    "DECOR_DIAMOND_CUSHION": "Diamond Cushion",
    "DECOR_BALL_CUSHION": "Ball Cushion",
    "DECOR_GRASS_CUSHION": "Grass Cushion",
    "DECOR_FIRE_CUSHION": "Fire Cushion",
    "DECOR_WATER_CUSHION": "Water Cushion",
    "DECOR_SNORLAX_DOLL": "Snorlax Doll",
    "DECOR_RHYDON_DOLL": "Rhydon Doll",
    "DECOR_LAPRAS_DOLL": "Lapras Doll",
    "DECOR_VENUSAUR_DOLL": "Venusaur Doll",
    "DECOR_CHARIZARD_DOLL": "Charizard Doll",
    "DECOR_BLASTOISE_DOLL": "Blastoise Doll",
    "DECOR_WAILMER_DOLL": "Wailmer Doll",
    "DECOR_REGIROCK_DOLL": "Regirock Doll",
    "DECOR_REGICE_DOLL": "Regice Doll",
    "DECOR_REGISTEEL_DOLL": "Registeel Doll",
}

NAMES_REV = {v: k for k, v in NAMES.items()}

SIZES = {
    "DECOR_NONE": (1, 1),
    "DECOR_ATTRACT_MAT": (3, 3),
    "DECOR_AZURILL_DOLL": (1, 1),
    "DECOR_BALL_CUSHION": (1, 1),
    "DECOR_BALL_POSTER": (1, 1),
    "DECOR_BALTOY_DOLL": (1, 1),
    "DECOR_BIG_PLANT": (2, 2),
    "DECOR_BLASTOISE_DOLL": (2, 2),
    "DECOR_BLUE_BALLOON": (1, 1),
    "DECOR_BLUE_BRICK": (1, 2),
    "DECOR_BLUE_POSTER": (1, 1),
    "DECOR_BLUE_TENT": (3, 3),
    "DECOR_BREAKABLE_DOOR": (1, 2),
    "DECOR_BRICK_CHAIR": (1, 1),
    "DECOR_BRICK_DESK": (3, 3),
    "DECOR_CAMP_CHAIR": (1, 1),
    "DECOR_CAMP_DESK": (3, 3),
    "DECOR_CHARIZARD_DOLL": (2, 2),
    "DECOR_CHIKORITA_DOLL": (1, 1),
    "DECOR_CLEFAIRY_DOLL": (1, 1),
    "DECOR_COLORFUL_PLANT": (2, 2),
    "DECOR_COMFORT_CHAIR": (1, 1),
    "DECOR_COMFORT_DESK": (3, 2),
    "DECOR_CUTE_POSTER": (1, 1),
    "DECOR_CUTE_TV": (1, 1),
    "DECOR_CYNDAQUIL_DOLL": (1, 1),
    "DECOR_DIAMOND_CUSHION": (1, 1),
    "DECOR_DITTO_DOLL": (1, 1),
    "DECOR_DUSKULL_DOLL": (1, 1),
    "DECOR_FENCE_LENGTH": (1, 1),
    "DECOR_FENCE_WIDTH": (1, 1),
    "DECOR_FIRE_BLAST_MAT": (3, 3),
    "DECOR_FIRE_CUSHION": (1, 1),
    "DECOR_FISSURE_MAT": (3, 3),
    "DECOR_GLASS_ORNAMENT": (1, 2),
    "DECOR_GLITTER_MAT": (1, 1),
    "DECOR_GOLD_SHIELD": (1, 2),
    "DECOR_GORGEOUS_PLANT": (2, 2),
    "DECOR_GRASS_CUSHION": (1, 1),
    "DECOR_GREEN_POSTER": (1, 1),
    "DECOR_GULPIN_DOLL": (1, 1),
    "DECOR_HARD_CHAIR": (1, 1),
    "DECOR_HARD_DESK": (3, 3),
    "DECOR_HEAVY_CHAIR": (1, 1),
    "DECOR_HEAVY_DESK": (3, 2),
    "DECOR_JIGGLYPUFF_DOLL": (1, 1),
    "DECOR_JUMP_MAT": (1, 1),
    "DECOR_KECLEON_DOLL": (1, 1),
    "DECOR_KISS_CUSHION": (1, 1),
    "DECOR_KISS_POSTER": (2, 1),
    "DECOR_LAPRAS_DOLL": (2, 2),
    "DECOR_LONG_POSTER": (2, 1),
    "DECOR_LOTAD_DOLL": (1, 1),
    "DECOR_MARILL_DOLL": (1, 1),
    "DECOR_MEOWTH_DOLL": (1, 1),
    "DECOR_MUDKIP_DOLL": (1, 1),
    "DECOR_MUD_BALL": (1, 1),
    "DECOR_NOTE_MAT": (1, 1),
    "DECOR_C_LOW_NOTE_MAT": (1, 1),
    "DECOR_D_NOTE_MAT": (1, 1),
    "DECOR_E_NOTE_MAT": (1, 1),
    "DECOR_F_NOTE_MAT": (1, 1),
    "DECOR_G_NOTE_MAT": (1, 1),
    "DECOR_A_NOTE_MAT": (1, 1),
    "DECOR_B_NOTE_MAT": (1, 1),
    "DECOR_C_HIGH_NOTE_MAT": (1, 1),
    "DECOR_PICHU_DOLL": (1, 1),
    "DECOR_PIKACHU_DOLL": (1, 1),
    "DECOR_PIKA_CUSHION": (1, 1),
    "DECOR_PIKA_POSTER": (2, 1),
    "DECOR_POKEMON_CHAIR": (1, 1),
    "DECOR_POKEMON_DESK": (1, 1),
    "DECOR_POWDER_SNOW_MAT": (3, 3),
    "DECOR_PRETTY_CHAIR": (1, 1),
    "DECOR_PRETTY_DESK": (3, 3),
    "DECOR_PRETTY_FLOWERS": (1, 2),
    "DECOR_RAGGED_CHAIR": (1, 1),
    "DECOR_RAGGED_DESK": (3, 2),
    "DECOR_RED_BALLOON": (1, 1),
    "DECOR_RED_BRICK": (1, 2),
    "DECOR_RED_PLANT": (1, 2),
    "DECOR_RED_POSTER": (1, 1),
    "DECOR_RED_TENT": (3, 3),
    "DECOR_REGICE_DOLL": (2, 2),
    "DECOR_REGIROCK_DOLL": (2, 2),
    "DECOR_REGISTEEL_DOLL": (2, 2),
    "DECOR_RHYDON_DOLL": (2, 2),
    "DECOR_ROUND_CUSHION": (1, 1),
    "DECOR_ROUND_TV": (1, 1),
    "DECOR_SAND_ORNAMENT": (1, 2),
    "DECOR_SEA_POSTER": (2, 1),
    "DECOR_SEEDOT_DOLL": (1, 1),
    "DECOR_SILVER_SHIELD": (1, 2),
    "DECOR_SKITTY_DOLL": (1, 1),
    "DECOR_SKY_POSTER": (2, 1),
    "DECOR_SLIDE": (2, 4),
    "DECOR_SMALL_CHAIR": (1, 1),
    "DECOR_SMALL_DESK": (1, 1),
    "DECOR_SMOOCHUM_DOLL": (1, 1),
    "DECOR_SNORLAX_DOLL": (2, 2),
    "DECOR_SOLID_BOARD": (1, 2),
    "DECOR_SPIKES_MAT": (3, 3),
    "DECOR_SPIN_CUSHION": (1, 1),
    "DECOR_SPIN_MAT": (1, 1),
    "DECOR_STAND": (4, 2),
    "DECOR_SURF_MAT": (3, 3),
    "DECOR_SWABLU_DOLL": (1, 1),
    "DECOR_THUNDER_MAT": (3, 3),
    "DECOR_TIRE": (2, 2),
    "DECOR_TOGEPI_DOLL": (1, 1),
    "DECOR_TORCHIC_DOLL": (1, 1),
    "DECOR_TOTODILE_DOLL": (1, 1),
    "DECOR_TREECKO_DOLL": (1, 1),
    "DECOR_TROPICAL_PLANT": (1, 2),
    "DECOR_TV": (1, 1),
    "DECOR_UNKNOWN_1x1": (1, 1),
    "DECOR_UNKNOWN_1x2": (2, 1),
    "DECOR_UNKNOWN_2x1": (1, 2),
    "DECOR_UNKNOWN_2x2": (2, 2),
    "DECOR_VENUSAUR_DOLL": (2, 2),
    "DECOR_WAILMER_DOLL": (2, 2),
    "DECOR_WATER_CUSHION": (1, 1),
    "DECOR_WYNAUT_DOLL": (1, 1),
    "DECOR_YELLOW_BALLOON": (1, 1),
    "DECOR_YELLOW_BRICK": (1, 2),
    "DECOR_ZIGZAG_CUSHION": (1, 1),
}